# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/steven/simplecar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/steven/simplecar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steven/simplecar/CMakeFiles /home/steven/simplecar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steven/simplecar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simplecar-picosat

# Build rule for target.
simplecar-picosat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplecar-picosat
.PHONY : simplecar-picosat

# fast build rule for target.
simplecar-picosat/fast:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/build
.PHONY : simplecar-picosat/fast

#=============================================================================
# Target rules for targets named simplecar

# Build rule for target.
simplecar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplecar
.PHONY : simplecar

# fast build rule for target.
simplecar/fast:
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/build
.PHONY : simplecar/fast

#=============================================================================
# Target rules for targets named libpicosat

# Build rule for target.
libpicosat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpicosat
.PHONY : libpicosat

# fast build rule for target.
libpicosat/fast:
	$(MAKE) -f CMakeFiles/libpicosat.dir/build.make CMakeFiles/libpicosat.dir/build
.PHONY : libpicosat/fast

#=============================================================================
# Target rules for targets named minisat

# Build rule for target.
minisat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minisat
.PHONY : minisat

# fast build rule for target.
minisat/fast:
	$(MAKE) -f minisat/CMakeFiles/minisat.dir/build.make minisat/CMakeFiles/minisat.dir/build
.PHONY : minisat/fast

aiger.o: aiger.c.o

.PHONY : aiger.o

# target to build an object file
aiger.c.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/aiger.c.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/aiger.c.o
.PHONY : aiger.c.o

aiger.i: aiger.c.i

.PHONY : aiger.i

# target to preprocess a source file
aiger.c.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/aiger.c.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/aiger.c.i
.PHONY : aiger.c.i

aiger.s: aiger.c.s

.PHONY : aiger.s

# target to generate assembly for a file
aiger.c.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/aiger.c.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/aiger.c.s
.PHONY : aiger.c.s

bfschecker.o: bfschecker.cpp.o

.PHONY : bfschecker.o

# target to build an object file
bfschecker.cpp.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/bfschecker.cpp.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/bfschecker.cpp.o
.PHONY : bfschecker.cpp.o

bfschecker.i: bfschecker.cpp.i

.PHONY : bfschecker.i

# target to preprocess a source file
bfschecker.cpp.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/bfschecker.cpp.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/bfschecker.cpp.i
.PHONY : bfschecker.cpp.i

bfschecker.s: bfschecker.cpp.s

.PHONY : bfschecker.s

# target to generate assembly for a file
bfschecker.cpp.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/bfschecker.cpp.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/bfschecker.cpp.s
.PHONY : bfschecker.cpp.s

carsolver.o: carsolver.cpp.o

.PHONY : carsolver.o

# target to build an object file
carsolver.cpp.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/carsolver.cpp.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/carsolver.cpp.o
.PHONY : carsolver.cpp.o

carsolver.i: carsolver.cpp.i

.PHONY : carsolver.i

# target to preprocess a source file
carsolver.cpp.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/carsolver.cpp.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/carsolver.cpp.i
.PHONY : carsolver.cpp.i

carsolver.s: carsolver.cpp.s

.PHONY : carsolver.s

# target to generate assembly for a file
carsolver.cpp.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/carsolver.cpp.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/carsolver.cpp.s
.PHONY : carsolver.cpp.s

checker.o: checker.cpp.o

.PHONY : checker.o

# target to build an object file
checker.cpp.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/checker.cpp.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/checker.cpp.o
.PHONY : checker.cpp.o

checker.i: checker.cpp.i

.PHONY : checker.i

# target to preprocess a source file
checker.cpp.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/checker.cpp.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/checker.cpp.i
.PHONY : checker.cpp.i

checker.s: checker.cpp.s

.PHONY : checker.s

# target to generate assembly for a file
checker.cpp.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/checker.cpp.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/checker.cpp.s
.PHONY : checker.cpp.s

data_structure.o: data_structure.cpp.o

.PHONY : data_structure.o

# target to build an object file
data_structure.cpp.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/data_structure.cpp.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/data_structure.cpp.o
.PHONY : data_structure.cpp.o

data_structure.i: data_structure.cpp.i

.PHONY : data_structure.i

# target to preprocess a source file
data_structure.cpp.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/data_structure.cpp.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/data_structure.cpp.i
.PHONY : data_structure.cpp.i

data_structure.s: data_structure.cpp.s

.PHONY : data_structure.s

# target to generate assembly for a file
data_structure.cpp.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/data_structure.cpp.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/data_structure.cpp.s
.PHONY : data_structure.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/main.cpp.s
.PHONY : main.cpp.s

mainsolver.o: mainsolver.cpp.o

.PHONY : mainsolver.o

# target to build an object file
mainsolver.cpp.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/mainsolver.cpp.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/mainsolver.cpp.o
.PHONY : mainsolver.cpp.o

mainsolver.i: mainsolver.cpp.i

.PHONY : mainsolver.i

# target to preprocess a source file
mainsolver.cpp.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/mainsolver.cpp.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/mainsolver.cpp.i
.PHONY : mainsolver.cpp.i

mainsolver.s: mainsolver.cpp.s

.PHONY : mainsolver.s

# target to generate assembly for a file
mainsolver.cpp.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/mainsolver.cpp.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/mainsolver.cpp.s
.PHONY : mainsolver.cpp.s

model.o: model.cpp.o

.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/model.cpp.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i

.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/model.cpp.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s

.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/model.cpp.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/model.cpp.s
.PHONY : model.cpp.s

utility.o: utility.cpp.o

.PHONY : utility.o

# target to build an object file
utility.cpp.o:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/utility.cpp.o
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/utility.cpp.o
.PHONY : utility.cpp.o

utility.i: utility.cpp.i

.PHONY : utility.i

# target to preprocess a source file
utility.cpp.i:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/utility.cpp.i
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/utility.cpp.i
.PHONY : utility.cpp.i

utility.s: utility.cpp.s

.PHONY : utility.s

# target to generate assembly for a file
utility.cpp.s:
	$(MAKE) -f CMakeFiles/simplecar-picosat.dir/build.make CMakeFiles/simplecar-picosat.dir/utility.cpp.s
	$(MAKE) -f CMakeFiles/simplecar.dir/build.make CMakeFiles/simplecar.dir/utility.cpp.s
.PHONY : utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... simplecar-picosat"
	@echo "... simplecar"
	@echo "... libpicosat"
	@echo "... minisat"
	@echo "... aiger.o"
	@echo "... aiger.i"
	@echo "... aiger.s"
	@echo "... bfschecker.o"
	@echo "... bfschecker.i"
	@echo "... bfschecker.s"
	@echo "... carsolver.o"
	@echo "... carsolver.i"
	@echo "... carsolver.s"
	@echo "... checker.o"
	@echo "... checker.i"
	@echo "... checker.s"
	@echo "... data_structure.o"
	@echo "... data_structure.i"
	@echo "... data_structure.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainsolver.o"
	@echo "... mainsolver.i"
	@echo "... mainsolver.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

